version: '3'
services:
  mongo:
    image: mongo
    container_name: fhir_mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - 'MONGO_INITDB_ROOT_USERNAME=${MG_USER-mongo-root}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MG_PASSWORD}'
    volumes:
      - '${DDEV_DIR-.}/mongo/database:/data/db'
      - '${DDEV_LOG-./log}/mongo/:/var/log/mongodb/'
      - '${DDEV_CONFIG-config}/mongo/mongod.conf:/etc/mongod.conf.orig'
    networks:
      - ddev
    ports:
      - '${MG_PORT-27017}:27017'
    restart: unless-stopped
  nginx:
    container_name: fhir_ngnix
    image: nginx
    volumes:
      - '${DDEV_CONFIG-.}/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - '${DDEV_LOG-./log}/nginx/:/var/log/nginx/'
      - '${DDEV_DIR-.}/nginx/cache/:/etc/nginx/cache'
      - '${DDEV_LETS_ENCRYPT-/etc/letsencrypt}:/etc/letsencrypt/'
      - '${DDEV_DIR-.}/www:/usr/share/nginx/html'
    ports:
      - '${HTTP_PORT-80}:80'
    networks:
      - ddev
    tty: true
  metadata:
    container_name: fhir_metadata
    image: fhir/fhir-metadata:1.0.0-SNAPSHOT
    environment:
      - fhir.urls[0]=http://patient:8080
      - fhir.urls[1]=http://appointment:8081
      - fhir.urls[2]=http://practitioner:8082
    volumes:
      - '${DDEV_LOG-./log}/metadata/:/var/log/nginx/'
    ports:
      - '${MTDAT_PORT-8008}:8080'
    networks:
      - ddev
    tty: true
  patient:
    container_name: fhir_patient
    image: fhir/fhir-patient:1.0.0-SNAPSHOT
    volumes:
      - '${DDEV_LOG-./log}/patient/:/var/log/nginx/'
    ports:
      - '${PATIENT_PORT-8080}:8080'
    networks:
      - ddev
    tty: true
  practitioner:
    container_name: fhir_practitioner
    image: fhir/fhir-practitioner:1.0.0-SNAPSHOT
    volumes:
      - '${DDEV_LOG-./log}/practitioner/:/var/log/nginx/'
    ports:
      - '${PRACT_PORT-8082}:8080'
    networks:
      - ddev
    tty: true
  appointment:
    container_name: fhir_appointment
    image: fhir/fhir-appointment:1.0.0-SNAPSHOT
    volumes:
      - '${DDEV_LOG-./log}/appointment/:/var/log/nginx/'
    ports:
      - '${APTMT_PORT-8081}:8080'
    networks:
      - ddev
    tty: true
  organization:
    container_name: fhir_organization
    image: fhir/fhir-organization:1.0.0-SNAPSHOT
    volumes:
      - '${DDEV_LOG-./log}/organization/:/var/log/nginx/'
    ports:
      - '${APTMT_PORT-8083}:8080'
    networks:
      - ddev
    tty: true
networks:
  ddev:
    driver: bridge
